version: "3.8"
services:
  chatters:
    image: jasperhaward/chatters-ui:latest
    restart: always
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
      - CHATTERS_SERVER_HTTP_URL=
      - CHATTERS_SERVER_WS_URL=
    ports:
      - "4050:80"
